spring.application.name=bhive-platform-local
server.port=8080


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

app.db.seed=false
app.db.secret-id=local/bhive/db
app.db.local-fallback-enabled=true
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/bhive_db?serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
