spring.application.name=bhive-platform-prod
server.port=8080


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR

app.db.seed=false
app.security.jwt.secret=${BHIVE_JWT_SECRET}
app.security.refresh-cookie.secure=true
app.security.refresh-cookie.same-site=${BHIVE_REFRESH_COOKIE_SAME_SITE:Lax}
app.db.secret-id=prod/bhive/db
